# Generated by Django 4.2.4 on 2023-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="c_type",
            field=models.CharField(
                choices=[("P", "President"), ("S", "Senator"), ("T", "Treasurer")],
                default="S",
                max_length=1,
            ),
        ),
    ]
